### PR TITLE
Handle IPv6 addresses in base URL

### LINKED ISSUE #109: Unable to Create PowerDNS Client with IPv6 Address as Host
### Description

When creating a client with an IPv6 address as host (in the format `http://[fd87:c6f0:8827::]/`), the function parseBaseURL incorrectly splits the address at the first ":", leading to an invalid hostname and port and incorect requests to PowerDNS: `http://[fd87:c6f0/api/v1/servers/...`

https://github.com/joeig/go-powerdns/blob/8716cf1eef95775003cfbddcbe097d3604d9ce48/powerdns.go#L115-L135

### Expected Behavior
The function should correctly handle IPv6 addresses enclosed in square brackets ([]).

### PR DESCRIPTION
**Pull request by joeig**
Resolves #109

### CODE REVIEW

File: powerdns.go [hunk 1]
```diff
@@ -113,24 +115,29 @@ func New(baseURL string, vHost string, options ...NewOption) *Client {
...
-	var port string
-	if len(hp) > 1 {
-		port = hp[1]
-	} else {
-		if u.Scheme == "https" {
-			port = "443"
-		} else {
-			port = "80"
+
+	hostname, port, err := net.SplitHostPort(parsedURL.Host)
```
Comment (Markovvn1) [inline powerdns.go:123]: It's probably too late, but I think we could also use `u.Hostname()` and `u.Port()` instead of `u.Host`:

```go
func parseBaseURL(baseURL string) (string, string, string, error) {
	u, err := url.Parse(baseURL)
	if err != nil {
		return "", "", "", err
	}
	hostname := u.Hostname()
	port := u.Port()
	if port == "" {
		if u.Scheme == "https" {
			port = "443"
		} else {
			port = "80"
		}
	}

	return u.Scheme, hostname, port, nil
}
```

It's working fine for me.

Comment (joeig) [reply powerdns.go:123]: This won't catch some invalid entries, e.g. when `baseURL` is `http://::8080`.
